**.concatenate**()

In [80]:
import numpy as np
import pandas as pd

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])
print(x)
print(y)
print(z)

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
np.concatenate((x,y,z)) # farklı 1 boyutlu numpy array'lerini satır şeklinde soldan sağa birleştirir.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((z,x,y)) # Farklı numpy array'ler yazıldıkları sıra ile birleştirilir.

array([7, 8, 9, 1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate([x.reshape(1,3), y.reshape(1,3), z.reshape(1,3)], axis = 0) # .reshape() yeniden boyutlandrıma; reshape(1,3); "satır(row) = 1" , "sütun(col.) = 3"; "axis = 0" --> satır şeklinde çalış

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.concatenate([x.reshape(1,3), y.reshape(1,3), z.reshape(1,3)], axis = 1) # 0" --> sütun  şeklinde çalış. 

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
a = np.random.randint(10, size = (2,3)) # random methodu randint fonkisyonu ile 0 - 10 arası(10 hariç) rastgele int type'ta elamanlar üretildi. size(2,3) satır = 2, sutun =3
b = np.random.randint(10, size = (2,3))

In [ ]:
a

array([[4, 9, 2],
       [4, 7, 8]])

In [ ]:
b

array([[9, 0, 7],
       [9, 8, 2]])

In [ ]:
np.concatenate((a,b), axis = 0) # 2B array'de axis = 0 satır oluşturacak şekilde alt alta birleştir.

array([[4, 9, 2],
       [4, 7, 8],
       [9, 0, 7],
       [9, 8, 2]])

In [ ]:
np.concatenate((a,b), axis = 1) # 2B array'de axis = 1 sutun oluşturacak şekilde yan yana birleştir.

array([[4, 9, 2, 9, 0, 7],
       [4, 7, 8, 9, 8, 2]])

**.split**()

In [ ]:
z = np.array([21, 24, 25, 32, 34, 10, 11, 12]) # el ile array oluşturma
z

array([21, 24, 25, 32, 34, 10, 11, 12])

In [ ]:
np.split(z, [2,3]) # split array'i parçalara böler (2,3) ->> 2. index'e kadar böler,  2. index'ten 3. indekse ve sonra geri kalanlar şeklinde

[array([21, 24]), array([25]), array([32, 34, 10, 11, 12])]

In [ ]:
np.split(z, [1,5]) # (1,5) ->> 1. index'e kadar böler,  1. index'ten 5. indekse ve sonra geri kalanlar ve sonra geri kalanlar şeklinde

[array([21]), array([24, 25, 32, 34]), array([10, 11, 12])]

In [ ]:
q = np.random.randint(10,50,8)
q

array([36, 47, 21, 18, 13, 16, 31, 11])

In [ ]:
np.split(q, 4) # int. değer yazılırsa, yazılan değer kadar(4) eşit parçaya böler. değere tam bölünmelidir.

[array([36, 47]), array([21, 18]), array([13, 16]), array([31, 11])]

In [ ]:
np.split(q, [3]) # yazılan indeks numarasından 2'ye böler.

[array([36, 47, 21]), array([18, 13, 16, 31, 11])]

In [ ]:
m = np.arange(20).reshape(5,4) # 5x4 
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
np.split(m, [1,3], axis = 0) # axis = 0 satırlarla çalışma. [1,3] 1. index'e kadar ->> ilk satır, 1 - 3 index(satır arası), geri kalan satırlar(indeks) şeklinde.

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [ ]:
np.split(m, [1,3], axis = 1) # # axis = 1 sutunlarla çalışma [1,3] 1. index'e kadar ilk sütunu, 1. - 3. index(sütun) arası sütunlar ve geri kalan sutunlar(indeks) şeklinde böler

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]), array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]), array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

**.sort()**

In [ ]:
k = np.array([2, 1, 4, 8, 11]) # array değerlerini sıralar

In [ ]:
np.sort(k) # 

array([ 1,  2,  4,  8, 11])

In [ ]:
str = np.array(["ab", "eg", "d", "b", "51"]) # array değerlerini sıralar
str

array(['ab', 'eg', 'd', 'b', '51'], dtype='<U2')

In [ ]:
np.sort(str) # string değer sıralama

array(['51', 'ab', 'b', 'd', 'eg'], dtype='<U2')

In [ ]:
twoD = np.random.randint(5, 50, (3,3)) # 5 - 50 arası rastgele değer 3x3, 2 Boyutlu
twoD

array([[12, 27,  9],
       [29, 41, 21],
       [34, 25, 16]])

In [ ]:
np.sort(twoD, axis = 0) # axis = 0 satır bazında. satır sayısı aşağı doğru artar... satır satır yukarıdan aşağı sıralar. 1. satırdaki en küçük değer sonra altına 2. satırdaki en küçük değer....

array([[12, 25,  9],
       [29, 27, 16],
       [34, 41, 21]])

In [ ]:
twoD

array([[12, 27,  9],
       [29, 41, 21],
       [34, 25, 16]])

In [ ]:
np.sort(twoD, axis = 1) # axis = 1 sutun bazında çalışma. sutun sayısı sola doğru artar... sutun sutun soladan sağa sıralar. 1. sütundaki en küçük değer sonra altına 2. satırdaki en küçük değer....

array([[ 9, 12, 27],
       [21, 29, 41],
       [16, 25, 34]])

**Bracket Indexing & Selection**

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[1::2] # 1 Boyutlu array; [start, stop, step] 1. index'ten başla sonuna kadar git 2 steple ilerle

array([1, 3, 5, 7, 9])

In [5]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [6]:
arr_2d[1] # 2 Boyutlu array [satır , sutun] 1. indexteki satır

array([20, 25, 30])

In [7]:
arr_2d[0,2] # 0. indexteki satır ile 2. indexteki sütunun kesişimi

15

In [8]:
arr_2d[:2,1:] # satıra baştan başla(indeks=0) 2. index'teki satıra kadar git, 1. index'teki sutundan başla sonuncu index'teki satıra kadar git

array([[10, 15],
       [25, 30]])

In [10]:
arr_2d[1,1] = 55 # yeni değer atama satır 1. index ile sutun 1. index kesişimini 55 yap


array([[ 5, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

**Fancy Index**

In [14]:
q = np.arange(20, 60, 3) # 3 step'le 20'den 60'a kadar array oluşturma
q

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59])

In [15]:
q[[1,3,5]] # [1,2,5] liste şeklinde index numaralırındaki elemanları getir. index = 1., 2. ve 5.

array([23, 29, 35])

In [17]:
arr2d =np.zeros((10,10), dtype = int) # 0(sıfır)'lardan 10x10 matris oluşturma
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
arr2d.shape[0]

10

In [20]:
for i in range(arr2d.shape[0]): # for döngüsü ile her seferinde arr2d array'inin shape numarasını al. "(arr2d.shape[0] = 10)"" olduğu için "range(0,10)" yazmış olduk
  arr2d[i] = i # arr2d for döngüsünden gelen 10'a kadar numaraları sırayla "[]" indeksleme ile karşılık gelen indeks'e yazdır
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [22]:
arr2d[[2,4,8,6]] # iki köşeli parantez 2b array oluşturur. arrayler yazılan sıra ile oluşur.

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

In [29]:
jj = np.arange(1,17).reshape(4,4) # 1 -17 arasında 4 satır 4 sütundan oluşan array oluşturur. # shape(4,4) = 4*4 = 16 = range(1,17) ya da reshape(2,8) yazabilirdik
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [30]:
jj[0,1] # [satır index = 0, sütun index = 1] şeklinde array elemanı seçme

2

In [32]:
jj[[1,2],[0,3]] # liste şeklinde index nuamrası.. [1,2] [0,3] liste index numarasına göre karşılıklı eşleşir = satır index no = 1, sütun index no = 0  satır index no = 2, sütun index no = 3

array([ 5, 12])

In [33]:
jj[[0,2,3],[0,1,3]] # liste şeklinde index nuamrası.. iste index numarasına göre karşılıklı eşleşir

array([ 1, 10, 16])

In [ ]:
jj[1,[1,3]] # python zekası :)) [1,[1,3]] = [1,1], [1,3] şeklinde 

In [34]:
jj [:,[1,3]] # [:] baştan başla sonuna kadar git  = tüm satırlar, bu satırlara kesişen 1. ve 3. index'teki sütunlar

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

**Selection On Condition**

In [37]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr > 4 # 4. index'ten büyük olanları True olarak getirir.

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
dd =np.array(["a", "b", "c"])
dd

In [ ]:
arr < 2 4 # 2. index'ten küçük olanları True olarak getirir.

In [45]:
bool_arr = arr > 4
arr[bool_arr] # conditiona göre seçim

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr[(arr < 3) | (arr > 8) & ((arr != 9) & (arr != 4))] # çoklu condition (okşul) operatörlerinin kullanımı

array([ 1,  2, 10])

**Array Broadcasting**

In [47]:
arr[:5] = 77 # seçilen elemanlara 77 atandı (yayma = broadcasting)

In [49]:
arr = np.arange(20, 30)
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [50]:
slice_of_arr = arr[0:6] # 0 - 6. index arası yeni değere atandı.bu şekilde orjinal array'de değişir.
slice_of_arr

array([20, 21, 22, 23, 24, 25])

In [52]:
slice_of_arr [:] = 99 # bu şekilde orjinal array'de değişir.
arr

array([99, 99, 99, 99, 99, 99, 26, 27, 28, 29])

In [53]:
arr_copy = arr.copy() # orjinal verimizin değişmesini istemiyorsak .copy() işlemi ile bir kopyası alınır. Büyük veride hafızaya dikkat !!
arr_copy

array([99, 99, 99, 99, 99, 99, 26, 27, 28, 29])

**Array Aritmetik İşlemler - ve (vectorisitation özelliği)**

In [93]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr2 = np.arange(20,30)
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [74]:
arr1 * arr1 # tüm elemanları kendisi ile çarpar.diğer işlemler içinde aynı Bu işlemler array'lerin vectorisitation (tüm elemanlara aynı işlemi uygulama) özellği  sayesinde olur.

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [72]:
arr1 * arr2 # iki farklı array indeks numaralarına göre çarpılır. diğer işlemler içinde aynı. not: eleman sayısı eşit olmalı

array([ 20,  42,  66,  92, 120, 150, 182, 216, 252, 290])

In [71]:
arr1 / arr2

array([0.05      , 0.0952381 , 0.13636364, 0.17391304, 0.20833333,
       0.24      , 0.26923077, 0.2962963 , 0.32142857, 0.34482759])

In [75]:
arr1 * 4 # tüm elemalar 4 ile çarpıldı

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [77]:
np.add((arr1,10) # tüm elemanları yazılan değerle topla

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [83]:
np.subtract((arr2),(arr1*4)) # çıkarma 

array([ 16,  13,  10,   7,   4,   1,  -2,  -5,  -8, -11])

In [98]:
np.multiply((arr1),((np.sqrt(arr2)) - (arr1/3))) # çarpma

array([ 4.13880262,  7.83181806, 11.07124728, 13.84999276, 16.16156409,
       18.        , 19.35980326, 20.23588605, 20.6235236 , 20.51831474])

In [102]:
np.divide((arr2),(np.max(arr1))) # bölme

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [103]:
np.max(arr2) # ya da "arr2.max()"" bu şekilde max değer

29

In [107]:
arr2.max() # max değer

29

In [104]:
np.min(arr1) # min değer

1

In [114]:
np.max(t, axis = 1) # axis'e göre max. değerler

array([ 4,  9, 14, 19])

In [115]:
np.min(t, axis = 1) # axis'e göre min. değerler

array([ 0,  5, 10, 15])

In [108]:
np.sqrt(arr2) # karekök

array([4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])

In [109]:
np.exp(arr1) #exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [129]:
t = np.random.randint(20,100,20).reshape(4,5)
t

array([[61, 87, 44, 20, 90],
       [34, 66, 96, 73, 85],
       [56, 26, 31, 26, 96],
       [20, 60, 43, 92, 27]])

In [130]:
np.std(t, axis = 1) #  axis =1' göre standard deviation hesaplama

array([26.40151511, 21.06561179, 26.90724809, 25.80387568])

In [134]:
np.std(t) standard deviation

26.95417407378679

In [133]:
np.mean(t) #mean (ortalama) hesaplama

56.65

In [126]:
np.median(t)  # medyan hesaplama

55.5

In [135]:
np.corrcoef(t) # correlation coefficient (korelasyon katsayısı)

array([[ 1.        , -0.08328478,  0.56532159, -0.59149101],
       [-0.08328478,  1.        ,  0.00564555,  0.23746518],
       [ 0.56532159,  0.00564555,  1.        , -0.68470729],
       [-0.59149101,  0.23746518, -0.68470729,  1.        ]])

In [136]:
np.var(arr2) # variance (varyans) hesaplama

8.25

In [137]:
np.percentile(t,75) # = IQR3

85.5

In [138]:
np.percentile(t,25) # = IQR1

30.0

In [139]:
np.random.seed(41)   # random değeri sabitler (içine yazılan sayının bir önemi yok.)
xarr = np.random.randn(3,5)
xarr

array([[-0.27071232,  0.10484805,  0.25052782, -0.92519997,  0.56714366],
       [-1.04018022, -0.15367595,  0.78985181, -1.22621585, -0.94800699],
       [-0.56965394, -0.97715021, -0.77063171, -0.03371129, -1.03285925]])

In [ ]:
import warnings
warnings.filterwarnings('ignore') # kod çalıştığı halde uyarı veren mesajları kaldırmak için kullanılır.